AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs6.10
    CodeUri: ../backend/vehicle.js
    Timeout: 180
    Environment:
      Variables:
        TABLE_NAME: !Ref Table
Resources:
  RegisterVehicleLambda:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: GmapsTest
      Policies: AmazonDynamoDBFullAccess
      Handler: vehicle.post
      DeploymentPreference:
        Type: Linear10PercentEvery1Minute
      Events:
        VehiclePost:
          Type: Api
          Properties:
            Path: '/api/vehicle'
            Method: post
  Table:
    Type: AWS::Serverless::SimpleTable
